### ISSUE TITLE
How to push notifications using Apprise

### ISSUE THREAD

**Issue by spysir** [l4rm4nd/F2BFilters#1]
Thanks a lot for this great project ! 
How to push notifications using Apprise ?

**Comment by l4rm4nd** [comment]
Hi @spysir, 

haven't used Apprise by myself. However, I would assume that you can create a bash script that sends such notifications via this channel. The script would get the fail2ban variables as input and process them. Basically alike to ``/action.d/telegram_notif.sh``.

Afterwards, you would just add your Apprise bash script to the actionban field of an action.d script:

Have a look at the following Telegram notification examples:

- https://github.com/l4rm4nd/F2BNPM/blob/main/data/action.d/telegram_notif.sh
- https://github.com/l4rm4nd/F2BNPM/blob/main/data/action.d/action-ban-docker-forceful-browsing.conf
