### ISSUE TITLE
Ban time? 

### ISSUE THREAD

**Issue by tobias86aa** [l4rm4nd/F2BFilters#5]
Is it possible to include the ban time in the telegram notification?

**Comment by l4rm4nd** [comment]
Fail2ban provides the following action variables, which you can use:

- `<bantime>`
- `<bancount>`

So you can adjust the action.d scripts to submit those values as telegram notification:

````
bash /data/action.d/telegram_notif.sh -b <ip> -r "forceful browsing on <F-CONTAINER><F-REQUESTHOST> (<name>) [banned <bancount> times; now for <bantime>s]"
````
I've added the changes to the relevant action scripts.

**Comment by tobias86aa** [comment]
Should it be something like that to when it comes to Cloudflare? It only seems like you modify the docker .conf file. 

Seems to be working for Cloudflare to

`bash /data/action.d/telegram_notif.sh -b <ip> -r  "above reasons on Cloudflare - <name> [banned <bancount> times; now for <bantime>s]"`

**Comment by l4rm4nd** [comment]
> Should it be something like that to when it comes to Cloudflare? It only seems like you modify the docker .conf file.
> 
> Seems to be working for Cloudflare to
> 
> `bash /data/action.d/telegram_notif.sh -b <ip> -r "above reasons on Cloudflare - <name> [banned <bancount> times; now for <bantime>s]"`

Works for cloudflare too.

I personally ban locally via iptables as well as additionally using cloudflare api. So in my case, I do not need the double notification. This is the reason for not updating the cloudflare action script. The telegram notifications there are already commented out and not enabled yet.

**Comment by tobias86aa** [comment]
But it seems to be showing in second. 

> > Should it be something like that to when it comes to Cloudflare? It only seems like you modify the docker .conf file.
> > Seems to be working for Cloudflare to
> > `bash /data/action.d/telegram_notif.sh -b <ip> -r "above reasons on Cloudflare - <name> [banned <bancount> times; now for <bantime>s]"`
> 
> Works for cloudflare too.
> 
> I personally ban locally via iptables as well as additionally using cloudflare api. So in my case, I do not need the double notification. This is the reason for not updating the cloudflare action script. The telegram notifications there are already commented out and not enabled yet.

Yes i try that. but it seems to be showing the ban time like this: 37158

Can the format be change to show like Day/hours/min ?

**Comment by l4rm4nd** [comment]
> But it seems to be showing in second.
> 
> > > Should it be something like that to when it comes to Cloudflare? It only seems like you modify the docker .conf file.
> > > Seems to be working for Cloudflare to
> > > `bash /data/action.d/telegram_notif.sh -b <ip> -r "above reasons on Cloudflare - <name> [banned <bancount> times; now for <bantime>s]"`
> > 
> > 
> > Works for cloudflare too.
> > I personally ban locally via iptables as well as additionally using cloudflare api. So in my case, I do not need the double notification. This is the reason for not updating the cloudflare action script. The telegram notifications there are already commented out and not enabled yet.
> 
> Yes i try that. but it seems to be showing the ban time like this: 37158
> 
> Can the format be change to show like Day/hours/min ?

The action ban command can be any Linux command. So you can convert the variable to your liking.
You can do this in the telegram_notif.sh script or beforehand in the actionban command.

**Comment by tobias86aa** [comment]
> > But it seems to be showing in second.
> > > > Should it be something like that to when it comes to Cloudflare? It only seems like you modify the docker .conf file.
> > > > Seems to be working for Cloudflare to
> > > > `bash /data/action.d/telegram_notif.sh -b <ip> -r "above reasons on Cloudflare - <name> [banned <bancount> times; now for <bantime>s]"`
> > > 
> > > 
> > > Works for cloudflare too.
> > > I personally ban locally via iptables as well as additionally using cloudflare api. So in my case, I do not need the double notification. This is the reason for not updating the cloudflare action script. The telegram notifications there are already commented out and not enabled yet.
> > 
> > 
> > Yes i try that. but it seems to be showing the ban time like this: 37158
> > Can the format be change to show like Day/hours/min ?
> 
> The action ban command can be any Linux command. So you can convert the variable to your liking. You can do this in the telegram_notif.sh script or beforehand in the actionban command.

Was trying to find some more information about this and how to set it up or how it can looks like. But it seems to be pretty hard to find anything around this.

**Comment by l4rm4nd** [comment]
> > > But it seems to be showing in second.
> > > > > Should it be something like that to when it comes to Cloudflare? It only seems like you modify the docker .conf file.
> > > > > Seems to be working for Cloudflare to
> > > > > `bash /data/action.d/telegram_notif.sh -b <ip> -r "above reasons on Cloudflare - <name> [banned <bancount> times; now for <bantime>s]"`
> > > > 
> > > > 
> > > > Works for cloudflare too.
> > > > I personally ban locally via iptables as well as additionally using cloudflare api. So in my case, I do not need the double notification. This is the reason for not updating the cloudflare action script. The telegram notifications there are already commented out and not enabled yet.
> > > 
> > > 
> > > Yes i try that. but it seems to be showing the ban time like this: 37158
> > > Can the format be change to show like Day/hours/min ?
> > 
> > 
> > The action ban command can be any Linux command. So you can convert the variable to your liking. You can do this in the telegram_notif.sh script or beforehand in the actionban command.
> 
> Was trying to find some more information about this and how to set it up or how it can looks like. But it seems to be pretty hard to find anything around this.

It's just bash:

````
bash /data/action.d/telegram_notif.sh -b <ip> -r "forceful browsing on <F-CONTAINER><F-REQUESTHOST> (<name>) [banned <bancount> times; now for $((<bantime> / 3600))h]"
````

**Comment by tobias86aa** [comment]
Thanks for the help.

`$((<bantime> / 86400))d:$((<bantime> / 3600))h:$((<bantime> / 3600))m]"`

Seems to be showing in days/hours/min now whit the above information. 

https://prnt.sc/Px_x2XdAekqp

**Comment by l4rm4nd** [comment]
> Thanks for the help.
> 
> `$((<bantime> / 86400))d:$((<bantime> / 3600))h:$((<bantime> / 3600))m]"`
> 
> Seems to be showing in days/hours/min now whit the above information. 
> 
> https://prnt.sc/Px_x2XdAekqp

Nice but your minutes show 72m, which is 1h 12m.

**Comment by tobias86aa** [comment]
> > Thanks for the help.
> > `$((<bantime> / 86400))d:$((<bantime> / 3600))h:$((<bantime> / 3600))m]"`
> > Seems to be showing in days/hours/min now whit the above information.
> > https://prnt.sc/Px_x2XdAekqp
> 
> Nice but your minutes show 72m, which is 1h 12m.

Yes I know I notes a  mistake that i did in the code  for min I had enter 60 instead of 3600. And the screenshot was taken before the change.
