### ISSUE TITLE
Stop Email Notifications

### ISSUE THREAD

**Issue by gregeeh** [l4rm4nd/F2BFilters#6]
Hi,

Thanks for sharing your knowledge it's greatly appreciated.

I have installed Vaultwarden and F2B in containers on my NAS and I'm accessing VW via Cloudflare Tunnel.  Followed your instructions and now failed logins are being banned at the CF level and I'm getting email notifications of failed attempts.

The problem is I'm getting email notifications of the F2B container being stopped, restarted or started.  Can these be stopped but still get the email notifications for failed login attempts?

My vaultwarden.local jail is below.

```
[vaultwarden]
enabled = true
port = 80,443,8081
filter = vaultwarden
banaction = %(banaction_allports)s
logpath = /remotelogs/vaultwarden/vaultwarden.log
maxretry = 3
bantime = 14400
findtime = 14400
chain = FORWARD
destemail = greg@domain.au
sender = greg@domain.net.au
sendername = Fail2ban
cfapikey = f720110xxxxxxxxxxxx241a7c476098bce8a
cfemail = greg@domain.net.au
action = %(action_cf_mwl)s
    iptables-allports
```

**Comment by l4rm4nd** [comment]
Hi @gregeeh,

this has nothing to do with this repo. 

Rather, it is a fail2ban configuration.

May read those:

- https://github.com/fail2ban/fail2ban/issues/3302
- https://serverfault.com/questions/998046/disable-fail2ban-email-notifications-on-a-service

**Comment by gregeeh** [comment]
Thank you for your comments, much appreciated.
